#!/bin/bash

# 检查是否为 root 权限
if [ "$EUID" -ne 0 ]; then
  echo "请以 root 权限运行此脚本。"
  exit 1
fi

# DNS 配置
DNS_TAIWAN_JAPAN_HONGKONG=("154.12.177.22" "8.8.8.8" "1.1.1.1")
DNS_SINGAPORE=("157.20.104.47" "8.8.8.8" "1.1.1.1")
RESOLV_CONF="/etc/resolv.conf"

# 解锁文件
unlock_file() {
  local file="$1"
  if lsattr "$file" 2>/dev/null | grep -q "i"; then
    echo "检测到 $file 被锁定，正在解锁..."
    chattr -i "$file" || { echo "解锁 $file 失败！"; exit 1; }
    echo "解锁成功。"
  fi
}

# 锁定文件
lock_file() {
  local file="$1"
  echo "正在锁定 $file..."
  chattr +i "$file" || { echo "锁定 $file 失败！"; exit 1; }
  echo "锁定成功。"
}

# 修改 DNS 配置
modify_dns() {
  local file="$1"
  shift
  local dns_servers=("$@")

  echo "正在修改 DNS 配置..."
  {
    echo "# Generated by set_dns.sh"
    for dns in "${dns_servers[@]}"; do
      echo "nameserver $dns"
    done
  } > "$file"

  if [ $? -eq 0 ]; then
    echo "DNS 修改成功：${dns_servers[*]}"
  else
    echo "DNS 修改失败，请检查文件权限或路径。"
    exit 1
  fi
}

# 获取实际文件路径
resolve_file() {
  local file="$1"
  if [ -L "$file" ]; then
    echo "$(readlink -f "$file")"
  else
    echo "$file"
  fi
}

# 获取当前 IP 所属地区
get_location() {
  echo "正在检测 IP 所属地区..."
  local location
  location=$(curl -s https://ipinfo.io | grep -E '"country"|region' | tr -d '"' | awk -F ': ' '{print $2}' | tr -d ',')
  echo "检测到地区为：$location"
  echo "$location"
}

# 主逻辑
main() {
  # 获取实际的 resolv.conf 文件路径
  local actual_resolv_conf
  actual_resolv_conf=$(resolve_file "$RESOLV_CONF")

  # 解锁文件
  unlock_file "$actual_resolv_conf"

  # 根据 IP 地区设置 DNS
  local location
  location=$(get_location)
  case "$location" in
    *Taiwan*|*Japan*|*Hong*)
      modify_dns "$actual_resolv_conf" "${DNS_TAIWAN_JAPAN_HONGKONG[@]}"
      ;;
    *Singapore*)
      modify_dns "$actual_resolv_conf" "${DNS_SINGAPORE[@]}"
      ;;
    *)
      echo "未知地区，不修改 DNS。"
      ;;
  esac

  # 锁定文件
  lock_file "$actual_resolv_conf"
}

main
