#!/bin/bash

# 检查是否为 root 权限
if [ "$EUID" -ne 0 ]; then
  echo "请以 root 权限运行此脚本。"
  exit 1
fi

# 定义 DNS 地址
DNS_TAIWAN_JAPAN_HONGKONG=("154.12.177.22" "8.8.8.8" "1.1.1.1")
DNS_SINGAPORE=("157.20.104.47" "8.8.8.8" "1.1.1.1")
RESOLV_CONF="/etc/resolv.conf"

# 解锁 /etc/resolv.conf（如果被锁定）
unlock_resolv_conf() {
  if lsattr "$RESOLV_CONF" | grep -q "i"; then
    echo "检测到 $RESOLV_CONF 被锁定，正在解锁..."
    chattr -i "$RESOLV_CONF"
    if [ $? -ne 0 ]; then
      echo "解锁 $RESOLV_CONF 失败，请检查文件系统或权限。"
      exit 1
    fi
    echo "解锁成功。"
  fi
}

# 锁定 /etc/resolv.conf
lock_resolv_conf() {
  echo "锁定 $RESOLV_CONF..."
  chattr +i "$RESOLV_CONF"
  if [ $? -ne 0 ]; then
    echo "锁定 $RESOLV_CONF 失败，请检查文件系统或权限。"
    exit 1
  fi
  echo "锁定成功。"
}

# 修改 /etc/resolv.conf
modify_dns() {
  local dns_servers=("$@")
  echo "正在修改 DNS 设置..."
  {
    echo "# Generated by set_dns.sh"
    for dns in "${dns_servers[@]}"; do
      echo "nameserver $dns"
    done
  } > "$RESOLV_CONF"

  if [ $? -eq 0 ]; then
    echo "DNS 修改成功：${dns_servers[*]}"
  else
    echo "DNS 修改失败，请检查文件权限。"
    exit 1
  fi
}

# 获取当前 IP 所属地区
get_location() {
  echo "正在检测 IP 所属地区..."
  local location
  location=$(curl -s https://ipinfo.io | grep -E '"country"|region' | tr -d '"' | awk -F ': ' '{print $2}' | tr -d ',')
  echo "检测到地区为：$location"
  echo "$location"
}

# 主逻辑
main() {
  # 解锁文件
  unlock_resolv_conf

  # 根据 IP 归属地选择 DNS
  location=$(get_location)
  case "$location" in
    *Taiwan*|*Japan*|*Hong*)
      modify_dns "${DNS_TAIWAN_JAPAN_HONGKONG[@]}"
      ;;
    *Singapore*)
      modify_dns "${DNS_SINGAPORE[@]}"
      ;;
    *)
      echo "未知地区，不修改 DNS。"
      ;;
  esac

  # 锁定文件
  lock_resolv_conf
}

main
