cat > /root/set_dns.sh << 'EOF'
#!/bin/sh

# 通用 DNS 设置脚本：支持 Alpine / Debian（自动处理 systemd-resolved / udhcpc）

DNS1="${1:-8.8.8.8}"
DNS2="${2:-1.1.1.1}"
DNS3="2001:4860:4860::8888"
DNS4="2606:4700:4700::1111"

RESOLV="/etc/resolv.conf"
BACKUP="/etc/resolv.conf.bak.$(date +%s)"

echo "[INFO] 使用 DNS："
echo "  $DNS1"
echo "  $DNS2"
echo "  $DNS3"
echo "  $DNS4"
echo

# ---- 先处理 systemd-resolved（Debian/Ubuntu 等）----
if command -v systemctl >/dev/null 2>&1; then
    if systemctl is-active --quiet systemd-resolved 2>/dev/null; then
        echo "[INFO] 检测到 systemd-resolved 正在运行，尝试停用并禁用开机自启..."
        systemctl disable --now systemd-resolved 2>/dev/null \
            && echo "[INFO] 已停用 systemd-resolved" \
            || echo "[WARN] 停用 systemd-resolved 失败，请手动检查"
    fi
fi

# ---- 备份 resolv.conf ----
if [ -e "$RESOLV" ] || [ -L "$RESOLV" ]; then
    cp "$RESOLV" "$BACKUP" 2>/dev/null || cp -a "$RESOLV" "$BACKUP" 2>/dev/null
    echo "[INFO] 已备份: $BACKUP"
fi

# ---- 删除 symlink（原先指向 systemd-resolved stub 的情况）----
if [ -L "$RESOLV" ]; then
    echo "[INFO] 检测到符号链接，删除 $RESOLV"
    rm -f "$RESOLV"
fi

# ---- Alpine: 禁止 udhcpc 覆盖 resolv.conf ----
if grep -qi "alpine" /etc/os-release 2>/dev/null; then
    mkdir -p /etc/udhcpc
    echo "RESOLV_CONF=no" > /etc/udhcpc/udhcpc.conf
    echo "[INFO] 已禁用 udhcpc 覆盖 resolv.conf"
fi

# ---- 写入新的 DNS ----
cat > "$RESOLV" << EOI
# Generated by set_dns.sh
nameserver $DNS1
nameserver $DNS2
nameserver $DNS3
nameserver $DNS4
EOI

echo "[INFO] 新的 resolv.conf："
cat "$RESOLV"
EOF

# 赋予权限
chmod +x /root/set_dns.sh

echo
echo "[INFO] 脚本已生成并赋权，立即执行："
echo

# 把所有参数传给 /root/set_dns.sh（支持两个 IPv4 DNS）
/root/set_dns.sh "$@"
